# Generated by Django 4.0 on 2021-12-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='type1',
            field=models.ImageField(max_length=2, upload_to=''),
        ),
    ]
