# Generated by Django 4.0 on 2021-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp1', '0002_alter_postmodel_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='type1',
            field=models.IntegerField(max_length=2),
        ),
    ]
