# Generated by Django 4.0 on 2022-01-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp1', '0003_alter_postmodel_type1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
